const REGIONS = [
  {
    id: "punta-cana",
    name: "Punta Cana",
    description: "El epicentro del turismo dominicano. Cap Cana, Bávaro, y Cabeza de Toro ofrecen las mejores oportunidades de inversión con altos retornos en renta vacacional.",
    description_en: "The epicenter of Dominican tourism. Cap Cana, Bavaro, and Cabeza de Toro offer the best investment opportunities with high vacation rental returns.",
    description_fr: "L'épicentre du tourisme dominicain. Cap Cana, Bávaro et Cabeza de Toro offrent les meilleures opportunités d'investissement avec d'excellents rendements locatifs saisonniers.",
    icon: "tree-palm",
    projectCount: 16,
    priceRange: "$97K - $876K",
    avgROI: "7-21%",
    coordinates: { lat: 18.58, lng: -68.37 },
    highlights: ["Mayor demanda turística", "CONFOTUR disponible", "Renta Airbnb premium"],
    highlights_en: ["Highest tourist demand", "CONFOTUR tax benefits available", "Premium Airbnb rental income"],
    highlights_fr: ["Plus forte demande touristique", "Avantages fiscaux CONFOTUR disponibles", "Revenus Airbnb premium"]
  },
  {
    id: "bayahibe",
    name: "Bayahibe",
    description: "Paraíso natural con playas vírgenes y turismo ecológico en crecimiento. Menor competencia y precios accesibles.",
    description_en: "A natural paradise with pristine beaches and a growing ecotourism scene. Less competition and accessible price points.",
    description_fr: "Un paradis naturel avec des plages vierges et un écotourisme en pleine croissance. Moins de concurrence et des prix accessibles.",
    icon: "palmtree",
    projectCount: 3,
    priceRange: "$165K - $499K",
    avgROI: "—",
    coordinates: { lat: 18.37, lng: -68.84 },
    highlights: ["Turismo ecológico", "Playas vírgenes", "Crecimiento sostenido"],
    highlights_en: ["Ecotourism destination", "Pristine beaches", "Sustained growth"],
    highlights_fr: ["Destination écotouristique", "Plages vierges", "Croissance soutenue"]
  },
  {
    id: "juan-dolio",
    name: "Juan Dolio / San Pedro",
    description: "A solo 45 min de Santo Domingo, combina playa y ciudad. Ideal para quienes buscan accesibilidad y plusvalía.",
    description_en: "Just 45 minutes from Santo Domingo, combining beach and city life. Ideal for those seeking accessibility and capital appreciation.",
    description_fr: "À seulement 45 minutes de Santo Domingo, alliant plage et vie urbaine. Idéal pour ceux qui recherchent accessibilité et plus-value.",
    icon: "waves",
    projectCount: 2,
    priceRange: "$179K - $361K",
    avgROI: "31.6%",
    coordinates: { lat: 18.43, lng: -69.85 },
    highlights: ["Cerca de Santo Domingo", "Alto ROI", "Playa Nueva Romana"],
    highlights_en: ["Close to Santo Domingo", "High ROI", "Playa Nueva Romana"],
    highlights_fr: ["Proche de Santo Domingo", "ROI élevé", "Playa Nueva Romana"]
  },
  {
    id: "distrito-nacional",
    name: "Distrito Nacional",
    description: "El corazón de Santo Domingo. Propiedades residenciales de alta gama para uso propio o renta a largo plazo.",
    description_en: "The heart of Santo Domingo. Upscale residential properties for personal use or long-term rental income.",
    description_fr: "Le cœur de Santo Domingo. Propriétés résidentielles haut de gamme pour usage personnel ou location à long terme.",
    icon: "building-2",
    projectCount: 2,
    priceRange: "$342K - $680K",
    avgROI: "—",
    coordinates: { lat: 18.47, lng: -69.93 },
    highlights: ["Capital del país", "Renta a largo plazo", "Uso residencial"],
    highlights_en: ["National capital", "Long-term rental income", "Residential living"],
    highlights_fr: ["Capitale du pays", "Revenus locatifs à long terme", "Usage résidentiel"]
  },
  {
    id: "bani",
    name: "Baní / Peravia",
    description: "Exclusivas villas de lujo con terrenos amplios. Para el inversionista que busca privacidad y exclusividad.",
    description_en: "Exclusive luxury villas on expansive lots. For the investor seeking privacy and exclusivity.",
    description_fr: "Villas de luxe exclusives sur de vastes terrains. Pour l'investisseur en quête d'intimité et d'exclusivité.",
    icon: "rocking-chair",
    projectCount: 2,
    priceRange: "$1.5M",
    avgROI: "—",
    coordinates: { lat: 18.28, lng: -70.33 },
    highlights: ["Villas de lujo", "Terrenos amplios", "Exclusividad"],
    highlights_en: ["Luxury villas", "Expansive lots", "Exclusivity"],
    highlights_fr: ["Villas de luxe", "Terrains spacieux", "Exclusivité"]
  },
  {
    id: "miches",
    name: "Miches / El Seibo",
    description: "La nueva frontera de desarrollo turístico. Terrenos frente al mar a precios de oportunidad antes del boom.",
    description_en: "The new frontier of tourism development. Oceanfront land at opportunity pricing before the boom.",
    description_fr: "La nouvelle frontière du développement touristique. Terrains en bord de mer à prix d'opportunité avant l'essor.",
    icon: "sunset",
    projectCount: 2,
    priceRange: "$200/m2",
    avgROI: "—",
    coordinates: { lat: 18.98, lng: -69.05 },
    highlights: ["Oportunidad temprana", "Frente al mar", "Desarrollo Club Med"],
    highlights_en: ["Early-stage opportunity", "Oceanfront", "Club Med development"],
    highlights_fr: ["Opportunité en phase initiale", "Front de mer", "Développement Club Med"]
  }
];
